### ISSUE TITLE
Templates should only be responsible for mapping the state to the UI inside inline-template ?

### ISSUE THREAD

**Issue by abrhambas01** [Te7a-Houdini/laravel-trix#10]
[Vue warn]: Error compiling template:

Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed., 

Is it because I'm using it inside an inline-template ? does that probably make this error show?

**Comment by goatatwork** [comment]
Seeing the same thing here. With an additional couple of messages..

```
[Vue warn]: Unknown custom element: <trix-toolbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]: Unknown custom element: <trix-editor> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

I just started troubleshooting this after installing it for the first time, so I haven't figured much out yet. At first glance, I see no interaction between the package and vue components other than these Vue warnings.  Hopefully those errors will help.

**Comment by Te7a-Houdini** [comment]
@abrhambas01 @goatatwork  can you try to wrap the trix rendring code with a dive element that contains [v-pre](https://vuejs.org/v2/api/#v-pre)

<div v-pre>
   //your trix code
</div>

**Comment by goatatwork** [comment]
Thank you for your work, @Te7a-Houdini 
When I tried that, the `Unknown custom element` messages went away, but the error that I was getting, that @abrhambas01 originally reported, remains.

```
[Vue warn]: Error compiling template:

Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.
```

and then a dump of the HTML, starting with my newly modified `<div v-pre="">`

**Comment by Te7a-Houdini** [comment]
@goatatwork after tracing the issue . i found that current implementation won't work with vue js as ```<style>``` can't be used inside vue js template . 

so if you wanted to use the configurations like ```hideTools``` it won't work . only what will work is the default @trix without any configuration passed.

**Comment by abrhambas01** [comment]
@Te7a-Houdini ,Mine's not using rendering code but just something like this 
```
<div class="mb-2 w-3/4" v-pre>
	<label for="name" class="block uppercase tracking-wide text-black-v2 text-xs font-bold mb-2">Complete Background and Details
	</label>
	@trix(App\CriminalInfo::class, 'complete_description')
</div>
```

**Comment by abrhambas01** [comment]
Yeah I think that's probably the reason. using it inside an inline-template could be the issue as inline templates don't want you to put the styles inside the span

**Comment by zeshan77** [comment]
I get the exact same error + the toolbar is non-functional. Does anyone solve this?

Thanks

**Comment by Te7a-Houdini** [comment]
@zeshan77 not yet i will try to work on a solution once i got time . if you have any thoughts to tackle it i would like to hear it out

**Comment by abrhambas01** [comment]
ok, I'm quite busy with the project that I am into but I will devote some time to find solutions for it

**Comment by Te7a-Houdini** [comment]
@abrhambas01 thanks a lot much appreciated :+1:

**Comment by zeshan77** [comment]
So I managed to get rid of the Vue error 
'Templates should only be responsible'
however the toolbar is still non-functional, it looks to be disabled.

Any rough idea what could be the reason? @Te7a-Houdini  @abrhambas01

**Comment by Te7a-Houdini** [comment]
@zeshan77 can you post what have you done to get rid of it . cause the main problem is that vue js won't parse any ```<style>``` tag inside the components for example this 

```html
<template>
     <style></style>
</template>
```

and since laravel-trix outputs ```<style>``` tag then the configuration won't work .

**Comment by zeshan77** [comment]
> @zeshan77 can you post what have you done to get rid of it . cause the main problem is that vue js won't parse any `<style>` tag inside the components for example this
> 
> ```
> <template>
>      <style></style>
> </template>
> ```
> 
> and since laravel-trix outputs `<style>` tag then the configuration won't work .

True, that was the problem. As I'm using trix editor inside Root vue component, so vue complains about the `<style>` tag. In my case, as I'm not using any custom styling, so I just commented out the following line in `Pipes->Styles.php`:

```php
$trix->html = "<style> {$trix->html} </style>";
```

I understand that it's a hack rather than a proper solution, I'll look into a proper solution at some point later once all the problems get resolved.

The thing which is worrying me now is the 'un functional tool bar' 

cc: @Te7a-Houdini

**Comment by Te7a-Houdini** [comment]
Thanks for your collaboration @zeshan77 @abrhambas01 @goatatwork .  i have released a new version which fixes vue js integration issues . just execute this command and everything should work fine **composer update te7a-houdini/laravel-trix**

**Comment by abrhambas01** [comment]
Oh Hey man, sorry I wasn't able to pay attention to your package as I was choosing a different trix-editor to work on since I need 2 deliver a software as fast as possible right now, but I will make sure to test out this package in my future projects, God speed to this project

**Comment by goatatwork** [comment]
@Te7a-Houdini, thank you for your work on this. I did the `composer update te7a-houdini/laravel-trix`. After that, I no longer get errors in the inspector. Yay.

The only remaining issue, which I can create a new issue for, if that's helpful, is that the toolbar seems to be not enabled, not attached to the textarea, or just generally not doing it's thing, formatting text. I am trying to get the example in the documentation working. I don't know what information would be helpful in troubleshooting.

**Comment by Te7a-Houdini** [comment]
@goatatwork got it . working on it right now

**Comment by Te7a-Houdini** [comment]
@goatatwork after a quick search i found that it's an issue from trix editor [#406](https://github.com/basecamp/trix/issues/406) . 

but a quick solution for it is to wrap ```@trix``` directive into ```<template>``` tag like this

```html
 <div id="app">
     <template>
       @trix(\App\User::class,'content')
    </template>
 </div>
```

**Comment by goatatwork** [comment]
Thanks again @Te7a-Houdini 

That seems to have done it. Things look pretty happy right now! Thank you.
