### ISSUE TITLE
Only retrieve the html without the editor.

### ISSUE THREAD

**Issue by piotrgulbis** [Te7a-Houdini/laravel-trix#14]
It's not apparent from the documentation how I can then display the model's trix content without the editor.

**Comment by Te7a-Houdini** [comment]
i think you can do something like this

```
$post->trixRichText()->where('field','content')->first();

```

also you can check [HasTrixRichText Trait for other methods](https://github.com/Te7a-Houdini/laravel-trix/blob/master/src/Traits/HasTrixRichText.php)

**Comment by piotrgulbis** [comment]
Thanks for your reply!

Unfortunately this doesn't return exactly what I need... 

        @foreach($posts as $post)
          <div class="flex flex-col w-1/3 m-3">
            <div>{{ $post->created_at }}</div>
            <div>{{ $post->title }}</div>
            <div>{{ $post->trixRichText()->where('field', 'content')->first() }}</div>
          </div>
        @endforeach

This returns the following:

    2019-12-13 11:03:00
    Test Test
    {"id":3,"field":"content","model_type":"App\\Post","model_id":3,"content":"<div>In hac habitasse platea dictumst. Phasellus a est. Fusce fermentum odio nec arcu.<br><br>Proin magna. Nunc nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia.<br><br>Vivamus euismod mauris. Fusce fermentum. Morbi mollis tellus ac sapien.<br><br>Donec interdum, metus et hendrerit aliquet, dolor diam sagittis ligula, eget egestas libero turpis vel mi. Duis lobortis massa imperdiet quam. Fusce a quam.<br><br>Quisque malesuada placerat nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.<\/div>","created_at":"2019-12-13 11:03:00","updated_at":"2019-12-13 11:03:00"}

**Comment by piotrgulbis** [comment]
Okay I think I've got it. 

    <div>{{ $post->trixRichText()->where('field', 'content')->first()->content }}</div>

...did the trick!

Thank you!
