### ISSUE TITLE
Render not working all methods 

### ISSUE THREAD

**Issue by phuongphally** [Te7a-Houdini/laravel-trix#16]
```php
<!-- inside view blade file -->

@trix($post, 'content')

{!! $post->trix('content') !!} //must use HasRichText trait in order for $model->trix() method work

{!! app('laravel-trix')->make($post, 'content') !!}

```

**Comment by phuongphally** [comment]
I use form share --create --and -- update

```php

<div class="form-group row">
    <label for="name" class="col-2 col-form-label">Content</label>
    <div class="col-10">
            @trix(isset($advertise)? $advertise: \App\Entities\Advertise::class, 'content')
    </div>
</div>

```

**Comment by Te7a-Houdini** [comment]
@phuongphally have you put ```@trixassets``` in the header ?

**Comment by phuongphally** [comment]
I already used

**Comment by Te7a-Houdini** [comment]
@phuongphally ok so is trix editor isn't showing at all . or only not showing when you use model object ```$advertise``` ?

**Comment by phuongphally** [comment]
It show when create screen. And not show when update screen

**Comment by Te7a-Houdini** [comment]
@phuongphally can you try to use another $model object . or if you are using vue js then you will need to do this 
```html
 <div id="app">
     <template>
       @trix(\App\User::class,'content')
    </template>
 </div>
```

i will close this issue since it's not a bug with the package . and possible something related to the application logic .

Thanks
