### ISSUE TITLE
Install issues with Laravel versions

### ISSUE THREAD

**Issue by mark-emery** [Te7a-Houdini/laravel-trix#18]
First attempt to install was with Laravel V6.6.2, didn't like that version so I upgraded to V6.8.0, the current version on 20-Dec-2019.

Still didn't like  Laravel version V6.8.0 which also appears in the list of versions it requires.

 Problem 1
    - Installation request for te7a-houdini/laravel-trix ^1.1 -> satisfiable by te7a-houdini/laravel-trix[1.1.0].
    - Conclusion: remove illuminate/container v6.8.0
    - Installation request for symfony/console (locked at v5.0.2) -> satisfiable by symfony/console[v5.0.2].
    - Conclusion: don't install illuminate/container v6.8.0
    - Conclusion: don't install laravel/framework **v6.8.0**
    - te7a-houdini/laravel-trix 1.1.0 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0|~5.8.0|~6.0 -> satisfiable by laravel/framework[v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.41, v5.5.42, v5.5.43, v5.5.44, v5.5.45, v5.5.46, v5.5.47, v5.5.48, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.24, v5.7.25, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.15, v5.8.16, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.21, v5.8.22, v5.8.23, v5.8.24, v5.8.25, v5.8.26, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, **v6.8.0,** v6.8.1, v6.9.0].
    - don't install laravel/framework v5.5.0|don't install illuminate/container v6.8.0

**Comment by Te7a-Houdini** [comment]
@mark-emery this is weird cause on fresh installation everything works perfectly. so can you post your composer.json file 

![Screenshot from 2019-12-20 00-21-26](https://user-images.githubusercontent.com/17250137/71214814-c310a500-22be-11ea-8e13-1de53d6edf14.png)
![Screenshot from 2019-12-20 00-19-01](https://user-images.githubusercontent.com/17250137/71214815-c3a93b80-22be-11ea-9f9c-93e896bb1d09.png)

**Comment by Te7a-Houdini** [comment]
@mark-emery no worries :+1:
