### ISSUE TITLE
How can we render stored content to view?

### ISSUE THREAD

**Issue by henryonsoftware** [Te7a-Houdini/laravel-trix#24]
I tried this package on Laravel 5.8 but I cannot render content to view.

I tried these methods but it showed an editor with stored content inside:
```
<!-- inside view blade file -->

@trix($post, 'content')

{!! $post->trix('content') !!} //must use HasTrixRichText trait in order for $model->trix() method work

{!! app('laravel-trix')->make($post, 'content') !!}
```
What I want is show text only, not show editable editor.

**Comment by Te7a-Houdini** [comment]
@henryonsoftware i think you can do this $post->content . as long as you don't want to show editor .

**Comment by henryonsoftware** [comment]
Thanks for reply, you are so fast.
I tried but not work!
I think `content` field does not have in Post table, you only can get it by use Trix instance.
You should write the full document (if possible)

**Comment by Te7a-Houdini** [comment]
@henryonsoftware yes you are right :+1: . feel free to PR this .
