### ISSUE TITLE
Not rendering configuration

### ISSUE THREAD

**Issue by realtarget** [Te7a-Houdini/laravel-trix#26]
Hey there,

i'm currently testing laravel-trix as a new editor for my webapp. Unfortunately the custom configuration is not rendering as expected.

Blade:
```
<div class="form-group">
<label for="exampleFormControlSelect2">Comment?</label>
@trix(\App\Events::class, 'description', [ 'containerElement'=>'div', 'id'=>'comment_editor', 'hideToolbar'=>'true', ])
</div>
```

Generated HTML:
![grafik](https://user-images.githubusercontent.com/4380964/75966694-098f9c00-5ecb-11ea-8dee-be605c833bc8.png)

Output:
![grafik](https://user-images.githubusercontent.com/4380964/75967316-ea453e80-5ecb-11ea-89d6-38b55bf1b6f1.png)

Any ideas?

**Comment by Te7a-Houdini** [comment]
@realtarget should be fixed in version 2.0.1
