### ISSUE TITLE
@trixassets not parsing

### ISSUE THREAD

**Issue by SDevogele** [Te7a-Houdini/laravel-trix#35]
Hi,

I've been able to use this package successfully on my local machine, but I can't get it to work on a shared server. It seems like blade isn't detecting @trixassets as a directive. It just echoes @trixassets at the top of the page.

I've double checked the files I've uploaded to the server. I've also uploaded the vendor folder.

I'm probably just doing something wrong, but could someone please point me in the right direction?

Thanks!

SDevogele

**Comment by Te7a-Houdini** [comment]
@SDevogele have you tried other blade directives on this shared server like @if or @foreach?

**Comment by SDevogele** [comment]
Yes, that's the weird thing. It seems like Laravel is just not recognizing @trixassets.

**Comment by SDevogele** [comment]
I've investigated this further, but I'm baffled.

So it works on one of my local machines, but not on my second local machine, and not on the shared server.

If I compare both my local machines, I don't see any difference: they run the same PHP version and as far as I know, the PHP settings should be the same on both machines.

Laravel is detecting all blade directives on all my machines, except just this one directive, and it works on only one machine.

What else could be causing this? Any ideas? Thanks!

**Comment by Te7a-Houdini** [comment]
@SDevogele have you tried to clear any cached views using . **php artisan view:clear**

**Comment by SDevogele** [comment]
Hi,

That did the trick on my second local machine, where it now works.

However, on the shared server, it still doesn't work. I used this piece of code:

`Artisan::call('cache:clear')`

I've also deleted the files in storage/framework/views.

Still no luck, however.

**Comment by Te7a-Houdini** [comment]
@SDevogele actually i don't know why it doesn't work on shared server . but since it's working locally then i think it's not a problem of the package .

but make sure that the package is installed on the shared server . maybe it's not installed

**Comment by SDevogele** [comment]
Yes, I see the package is in the vendor folder. I also have the configuration file in the config folder.

It's a shame I can't get it to work on the shared server. It seems like a very decent package, but I'm afraid there's no other option than uninstall it.

Anyway, thanks for your help.

**Comment by Te7a-Houdini** [comment]
@SDevogele thanks and good luck .
