### ISSUE TITLE
trix_rich_texts table is not affected

### ISSUE THREAD

**Issue by AhmedRamadan30** [Te7a-Houdini/laravel-trix#39]
### Salam
**Thank you for this beautiful package**
I got a Confusing problem When I add a post, the trix_rich_texts does not store a new record, it still empty and so I cannot store or show the Irish text content
I will attach every part from code here
![1](https://user-images.githubusercontent.com/56490896/87938461-eb4fc480-ca96-11ea-8d67-972e7ae56aa6.PNG)
![2](https://user-images.githubusercontent.com/56490896/87938470-ed198800-ca96-11ea-99a3-eabdf2f8efde.PNG)
![3](https://user-images.githubusercontent.com/56490896/87938472-edb21e80-ca96-11ea-9454-c7e7bc5b3afe.PNG)
![4](https://user-images.githubusercontent.com/56490896/87938473-ee4ab500-ca96-11ea-8164-49f3133b972b.PNG)
I hope you reply quickly
Thanks

**Comment by Te7a-Houdini** [comment]
hey @AhmedRamadan30  so you are facing two problems as follow : 

- first one is the rich text editor isn't shown
-  second one is when storing you find the table is empty 
right ?

**Comment by mhansen-upscale** [comment]
Hey! I have the exact same issue. Everything works like a charm except storing into database.

**Comment by Te7a-Houdini** [comment]
@mhansen-upscale can you show me a screenshot of your Model that uses HasTrixRichText

**Comment by mhansen-upscale** [comment]
This is the model 

<img width="714" alt="Bildschirmfoto 2020-07-21 um 20 14 38" src="https://user-images.githubusercontent.com/68611164/88091119-e706d280-cb8e-11ea-9665-304d4bed6878.png">

**Comment by Te7a-Houdini** [comment]
@mhansen-upscale try to remove $fillable . and use $guarded = [];

**Comment by mhansen-upscale** [comment]
great, that worked, thanks. Whats wrong with fillable at this point?

**Comment by Te7a-Houdini** [comment]
@mhansen-upscale i think nothing wrong . can you try to add content-trixFields to the fillable and check it too

**Comment by mhansen-upscale** [comment]
perfect, works as well!

**Comment by Te7a-Houdini** [comment]
cool . @AhmedRamadan30 i think the fix for your issue is same as approve . 

either set $guarded = []; . or add the field to fillable

**Comment by AhmedRamadan30** [comment]
I tried all solutions,
1 - ```protected $guarded = [];```
2 - ```protected $fillable = ['title', 'post-trixFields'];```
3 - ```protected $fillable = ['title', 'content-trixFields'];```
4 - ```protected $guarded = [];```
    ```    protected $fillable = ['title', 'post-trixFields'];```
after all, the `trix_rich_texts` table does not store a new record

**Comment by Te7a-Houdini** [comment]
@AhmedRamadan30 have you tried to do  **dd(request()->all())** inside the controller and see how the data look like

**Comment by AhmedRamadan30** [comment]
Thanks, I found the problem, I typed the model name incorrectly (I typed Event instead of Post) and that's because I made a separated project to test Trix. and in the original project, the model name was "Event"

**Comment by AhmedRamadan30** [comment]
I face another problem in showing images upload. the images are uploaded successfully and saved in ```Storage/public```
but when I show the whole article, images are not shown.  Why its link is ``` Storage/image_name``` , not ```Storage/public/image_name```?
![1](https://user-images.githubusercontent.com/56490896/88163709-5f16dc00-cc13-11ea-980c-2e8be3ea5dc6.PNG)
![2](https://user-images.githubusercontent.com/56490896/88163712-60480900-cc13-11ea-8243-481259b98bca.PNG)
