### ISSUE TITLE
Can this work in an SPA?

### ISSUE THREAD

**Issue by jcsoriano** [Te7a-Houdini/laravel-trix#7]
Hi, thank you for this package! Looks really good!

Just a question - can this work in an SPA? Is there any way we can render the trix markup using javascript instead of using the blade `@trix` directive?

**Comment by Te7a-Houdini** [comment]
hey 

i think there's a way  like this [Test Case](https://github.com/Te7a-Houdini/laravel-trix/blob/master/tests/Unit/LaravelTrixTest.php#L12)

```php
$post->trix('content')->__toString();
```
