### ISSUE TITLE
A model don`t see  trix fields

### ISSUE THREAD

**Issue by DmitryNeposidjaka** [Te7a-Houdini/laravel-trix#8]
It is doesn't work from scratch!
Here is my model:
![image](https://user-images.githubusercontent.com/13102394/68781650-c3bf7700-0640-11ea-943b-f12f75bddc94.png)

Here is my form: 

![image](https://user-images.githubusercontent.com/13102394/68781678-cde17580-0640-11ea-972f-3130e76851d4.png)

Post::create(request()->all()); 
I am getting an error that says the content field doesn`t have a default value. So what a problem?
why does the model cant see trix fields?

**Comment by Te7a-Houdini** [comment]
i think cause you have a content field in posts table that is not null .

so my suggestion would be :

- remove the `$fillable` array from Post model . 

- try to use `@trix(\App\Post::class, 'description)`

and check if this solved the issue
