### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry'

### ISSUE THREAD

**Issue by abrhambas01** [Te7a-Houdini/laravel-trix#9]
> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "trix-toolbar" has already been used with this registry error in trix editor,

Is it because I have vue-trix installed on npm ? should I remove any instance of vue-trix in my app ?

**Comment by Te7a-Houdini** [comment]
@abrhambas01 try to remove vue-trix and check if it fixed the issue

**Comment by abrhambas01** [comment]
in the `package.json` file or just in the bootstrap.js or in the entry js file ?

**Comment by Te7a-Houdini** [comment]
@abrhambas01 in package.json file . also check [how to remove an npm package from here](https://stackoverflow.com/questions/13066532/how-to-uninstall-npm-modules-in-node-js)

**Comment by abrhambas01** [comment]
I am using yarn so just yarn install probably would do
